config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :jobs
  resources :periods
  resources :job_job_associations
  resources :event_job_period_associations

  resources :users
  resources :microposts, only: [:create, :destroy]

  root 'static_pages#home'
  get 'home'       => 'static_pages#home'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'  => 'static_pages#impressum'
  get 'tcpsp'      => 'static_pages#tcpsp'

  get 'offer'      => 'static_pages#offer'

  get  'signup'   => 'users#new'

  get   'login'   => 'sessions#new'
  post  'login'     => 'sessions#create'
  post  'logout'  => 'sessions#destroy'
  delete 'logout'  => 'sessions#destroy'

  post "periods/change", as: :change_periods

  get 'sessions/new'
  get 'users/new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def offer
  end

  def about
  end

  def contact
  end

  def impressum
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Über uns") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | EvenTraum</title>
  </head>
  <body>


  <br>

  <h1>Über die Gründer</h1>
  <br>
  <div style="text-align:right">
  <div class="image">
    <div style=><%=image_tag("Xelat.jpg", width: "140", height: "200")%></div>
    <p> Xelat Akcam</p>
  </div>

  <div class="image">
    <div style=><%=image_tag("Hayat.jpg", width: "140", height: "200")%></div>
    <p> Hayat Boulakhrif </p>
  </div>

  <div class="image">
    <div style=><%=image_tag("Nadia.jpg", width: "150", height: "200")%></div>
    <p> Nadia Kruszewski </p>
  </div>
  </div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <p>Wir sind die drei Gründerinnen der EvenTraum GmbH.
    Nach erfolgreichem Abschluss Bachelor of Science der Wirtschaftswissenschaft an der Gottfried Wilhelm Leibniz Universität Hannover studieren wir nun gemeinsam den Master of Sciecne im Major Operations Management and Research.... </p>
  <br>
  <h1>Über das Unternehmen</h1>
  <p>Im Rahmen der Veranstaltung „Entwicklung von Anwendungssystemen“
    am <a href="http://www.prod.uni-hannover.de">Institut für Produktionswirtschaft</a> im Master „Operations Management and Research“
    an der Gottfried Wilhelm Leibniz Universität Hannover ist die Web-Applikation „EvenTraum“ entwickelt worden.<br>
    Die Web-Applikation basiert auf dem <a href="http://3rd-edition.railstutorial.org/">Ruby on Rails Tutorial – Learn Web Development with Rails</a> von Michael Hartl.<br>
    Mit der Web-Applikation „EvenTraum“ kann ein Multi-Projekt-Planungsproblem gelöst werden.
  </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Kontakt") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>Kontakt</h1>
<br>
<p>Kontaktieren Sie bei Rückfragen oder Anregungen gerne das EvenTraum-Team.
  <br><br>
<%= mail_to ("xelat.akcam@gmail.com"), "Xelat Akcam", :style=> "font-weight: bold" %>
<div style="text-align:left"><%=image_tag("email.png", size: "25") + "  xelat.akcam@gmail.com" %></div>
<br><br>
<%= mail_to ("ha.boulakhrif@web.de"), "Hayat Boulakhrif", :style=> "font-weight: bold" %><br><br>
<div style=""><%=image_tag("email.png", size: "25") + "  ha.boulakhrif@web.de" %></div>
<br><br>
<%= mail_to ("nadia.kruszewski@yahoo.de"), "Nadia Kruszewski", :style=> "font-weight: bold" %><br><br>
<div style="text-align:left"><%=image_tag("email.png", size: "25") + "  nadia.kruszewski@yahoo.de" %></div>
</p>
</body>
</html>


app/views/static_pages/home.html.erb
<% provide(:title, "Startseite") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EvenTraum </title>
</head>
<body>
  <div style="text-align:right"><%=image_tag("logo.png") %></div>
</body>
</html>

app/views/static_pages/impressum.html.erb
<% provide(:title, "Impressum") %>
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %> | EvenTraum</title>
  </head>
  <body>

  <h1>Impressum</h1>

  <p>
    EvenTraum GmbH<br>
    c/o Leibniz Universität Hannover<br>
    Institut für Produktionswirtschaft<br>
    Königsworther Platz 1<br>
    D-30167 Hannover<br><br>
    Vertretungsberichtsberechtigter Vorstand:<br>
    Xelat Akcam<br>
    Hayat Boulakhrif<br>
    Nadia Kruszewski
  </p>

  </body>

</html>

app/views/static_pages/offer.html.erb
<% provide(:title, "Angebot") %>
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title) %> | EvenTraum</title>
</head>
<body>
<h1>EvenTraum realisiert das Event Ihrer Träume</h1>
<br>
<p>Kreiieren Sie Ihr persönliches Event<br><br>
  Entscheiden Sie selbst, was zu Ihrem persönlichen EvenTraum dazu gehört:
  Ob Catering, Entertainment oder die passende Raumdekoration, wir kümmern uns für Sie um all Ihre Wünsche.
</p>
</body>
</html>

app/views/static_pages/tcpsp.html.erb
<% provide(:title, 'Eventplanung') %>
<h1>Eventplanung</h1>
<p>
  Hier können Sie die Daten der Multi-Projekt-Planung verwalten  <br><br>

  <%= link_to "Hier geht es zur Verwaltung der Events!", events_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Vorgänge!", jobs_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Perioden!", periods_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Vorgänger-Nachfolger-Beziehungen!", job_job_associations_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Events-Vorgänge-Perioden-Zuordnungen!", event_job_period_associations_path %><br>

</p>

<br>

<% if logged_in? %>


<% end %>
