config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :jobs
  resources :periods
  resources :job_job_associations
  resources :event_job_period_associations

  resources :users
  resources :microposts, only: [:create, :destroy]

  root 'static_pages#home'
  get 'home'       => 'static_pages#home'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'  => 'static_pages#impressum'
  get 'tcpsp'      => 'static_pages#tcpsp'

  get 'offer'      => 'static_pages#offer'

  get  'signup'   => 'users#new'

  get   'login'   => 'sessions#new'
  post  'login'     => 'sessions#create'
  post  'logout'  => 'sessions#destroy'
  delete 'logout'  => 'sessions#destroy'

  post "periods/change", as: :change_periods

  get 'sessions/new'
  get 'users/new'

end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :events, through: :event_job_period_associations
  has_many :jobs, through: :event_job_period_associations
  has_many :event_job_period_associations, dependent: :destroy
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all
    @number_of_periods = Period.count
    if @mynumber_of_periods = nil
      @mynumber_of_periods=@number_of_periods
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @periods }
    end
  end

  def change
    @mynumber_of_periods = params[:mynewnumber].to_i
    @number_of_periods = Period.count
    number_of_missing_periods=@mynumber_of_periods - @number_of_periods

    if number_of_missing_periods > 0
      @events = Event.all
      @jobs = Job.all
      (1..number_of_missing_periods).each do |number|
        name="t#{number+@number_of_periods}"
        @new_period=Period.create!(name: name)
        @events.each { |event|
        @jobs.each { |job|
          EventJobPeriodAssociation.create(event_id: event.id, job_id: job.id, period_id: @new_period.id)
        }}
      end
    end

    if number_of_missing_periods < 0
      (@mynumber_of_periods +1 ..@number_of_periods).each do |number|
        name="t#{number}"
        Period.find_by_name(name).destroy
      end
    end


    @periods = Period.all
    render :template => "periods/index"

  end

  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Die Periode wurde erfolgreich angelegt.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to @period, notice: 'Die Periode wurde erfolgreich aktualisiert.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to periods_url, notice: 'Die Periode wurde entfernt.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:name, :addcap)
    end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Perioden anlegen' %><br>
    <%= f.text_field :name, type: "number", min:0, required:"required" %>
  </div>
  <div class="field">
    <%= f.label 'Zusatzkapazität anlegen' %><br>
    <%= f.number_field :addcap, type: "number", min:1, required:"required" %>
  </div>
  <div class="actions">
    <%= f.submit 'Perioden anlegen oder aktualisieren' %>
  </div>
<% end %>

app/views/periods/edit.html.erb
<h1>Perioden aktualisieren</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @period %> |
<%= link_to 'Zurück', periods_path %>

app/views/periods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Übersicht der Perioden</h1>

<table id="periods" class="display">
  <thead>
    <tr>
      <th>Periode</th>
      <th>Zusatzkapazität</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= period.name %></td>
        <td><%= period.addcap %></td>
        <td><%= link_to 'Anzeigen', period %></td>
        <td><%= link_to 'Ändern', edit_period_path(period) %></td>
        <td><%= link_to 'Löschen', period, method: :delete, data: { confirm: 'Möchten Sie diesen Eintrag sicher löschen?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <b>Anzahl Perioden:</b>
  <%= @number_of_periods %>
</p>


<%= form_tag change_periods_path %>
<div class="field">
  <%= label_tag :mynewnumber, "Tragen Sie hier bitte die gewünschte Anzahl von Perioden ein:" %>
  <%= text_field_tag :mynewnumber, @mynumber_of_periods  %>
</div>
<%= submit_tag "Anzahl der Perioden anpassen" %>

<br>

<%= link_to 'Neue Periode', new_period_path %>
<br>  <br><%= link_to 'Zurück zur Eventplanung', tcpsp_path %>

app/views/periods/new.html.erb
<h1>Neue Periode</h1>

<%= render 'form' %>

<%= link_to 'Zurück', periods_path %>

app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Periode:</strong>
  <%= best_in_place @period, :name %>
</p>

<p>
  <strong>Zusatzkapazität:</strong>
  <%= best_in_place @period, :addcap %>
</p>

<%= link_to 'Ändern', edit_period_path(@period) %> |
<%= link_to 'Zurück', periods_path %>