config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :jobs
  resources :periods
  resources :job_job_associations
  resources :event_job_period_associations

  resources :users
  resources :microposts, only: [:create, :destroy]

  root 'static_pages#home'
  get 'home'       => 'static_pages#home'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'impressum'  => 'static_pages#impressum'
  get 'tcpsp'      => 'static_pages#tcpsp'

  get 'offer'      => 'static_pages#offer'

  get  'signup'   => 'users#new'

  get   'login'   => 'sessions#new'
  post  'login'     => 'sessions#create'
  post  'logout'  => 'sessions#destroy'
  delete 'logout'  => 'sessions#destroy'

  post "periods/change", as: :change_periods

  get 'sessions/new'
  get 'users/new'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :jobs, through: :event_job_period_associations
  has_many :periods, through: :event_job_period_associations
  has_many :event_job_period_associations, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
      @events = Event.all
    end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save


        format.html { redirect_to @event, notice: 'Herzlichen Dank. Ihr Auftrag wurde erfolgreich erstellt. Sie haben eine Bestätigungsemail erhalten. In Kürze werden wir Sie kontaktieren.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Das Event wurde erfolgreich aktualisiert.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Das Event wurde entfernt.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :occasion, :deadline)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Eventnummer" %><br>
    <%= f.text_field :name, type: "number", min:1, required: "required" %>
  </div>
  <div class="field">
    <%= f.label "Anlass" %><br>
    <%= f.text_field :occasion, type: "text", pattern: "[A-Za-z\040]{1,}", title:"Bitte keine Zahlen und Sonderzeichen verwenden.", required: "required"  %>
  </div>
  <div class="field">
    <%= f.label "Eventzeitpunkt" %><br>
    <%= f.number_field :deadline, type: "number", min:7, required: "required" %>
  </div>
  <div class="actions">
    <%= f.submit 'Event anlegen', {:class => "btn btn-primary"} %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, "Events") %>
<h1>Bearbeitung der Events</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @event %> |
<%= link_to 'Zurück', events_path %>

app/views/events/index.html.erb
<% provide(:title, "Events") %>

<% if current_user.admin? && !current_user?(users_path) %>

    <h1>Übersicht der Events</h1>
    <table id="events" class="display">
      <thead>
      <tr>
        <th>Name</th>
        <th>Anlass</th>
        <th>Periode</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.occasion %></td>
            <td><%= event.deadline %></td>
            <td><%= link_to 'Anzeigen', event %></td>
            <td><%= link_to 'Bearbeiten', edit_event_path(event) %></td>
            <td><%= link_to 'Löschen', event, method: :delete, data: { confirm: 'Möchten Sie diesen Eintrag sicher löschen?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>

    <%= link_to 'Neues Event erstellen', new_event_path %><br><br>
    <%= link_to 'Zurück zur Eventplanung', tcpsp_path %>

<% else %>

    <h1>Mein neues Event</h1>
    <p>Wir freuen uns, dass Sie sich dazu entschieden haben, Ihr nächstes Event von unserem EvenTraum-Team realisieren zu lassen.<br>
    Bitte teilen Sie uns nachfolgend Ihre genauen Vorstellungen und Anforderungen mit, damit wir einen Einblick in Ihren Traum gewinnen können.</p><br>
    <%= button_to "Neues Event in Auftrag geben" , new_event_path, method: :get, :class => "btn btn-primary" %>

<% end %>

app/views/events/new.html.erb
<% provide(:title, "Events") %>

<h1>Neues Event</h1>

<%= render 'form' %>

<%= link_to 'Zurück', events_path %>

app/views/events/show.html.erb
<% provide(:title, "Events") %>

<h1>Auftragsdetails zum Events</h1>

<p>
  <strong>Name:</strong>
  <%= best_in_place @event, :name %>
</p>

<p>
  <strong>Anlass:</strong>
  <%= best_in_place @event, :occasion %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= best_in_place @event, :deadline %>
</p>

<%= link_to 'Bearbeiten', edit_event_path(@event) %> |
<%= link_to 'Zurück', events_path %>